spring:
  application:
    name: Cloud_Config_Server
    
    cloud:
     config:
       server:
           git:
            uri:https://github.com/ashokitschool/congiguration_properties
            clone-on-start:true
      
 
server:
  port: 7071            
            
